export const visa: Array<string> = [
  'D-2',
  'D-4',
  'D-10',
  'C-4',
  'F-2',
  'F-4',
  'F-5',
  'F-6',
  'H-1',
];

export const phone = ['010'];

export const gender = ['Male', 'Female', 'None'];

export const languageList = [
  'English',
  'Korean',
  'Vietnamese',
  'Uzbek',
  'Turkish',
];

export const country = [
  'Ghana',
  'Gabon',
  'Guyana',
  'Gambia',
  'Guernsey',
  'Guadeloupe',
  'Guatemala',
  'Guam',
  'Grenada',
  'Greece',
  'Greenland',
  'Guinea',
  'Guinea-Bissau',
  'Namibia',
  'Nauru',
  'Nigeria',
  'Antarctica',
  'Republic of South Sudan',
  'South Africa',
  'Netherlands',
  'Netherlands Antilles',
  'Nepal',
  'Norway',
  'Norfolk Island',
  'New Caledonia',
  'New Zealand',
  'Niue',
  'Niger',
  'Nicaragua',
  'Korea, Republic of',
  'Denmark',
  'Dominican Republic',
  'Dominica',
  'Germany',
  'East Timor',
  "Lao People's Democratic Republic",
  'Liberia',
  'Latvia',
  'Russian Federation',
  'Lebanon',
  'Lesotho',
  'Reunion',
  'Romania',
  'Luxembourg',
  'Rwanda',
  'Libyan Arab Jamahiriya',
  'Lithuania',
  'Liechtenstein',
  'Madagascar',
  'Martinique',
  'Marshall Islands',
  'Mayotte',
  'Macau',
  'Republic of Macedonia',
  'Malawi',
  'Malaysia',
  'Mali',
  'Isle of Man',
  'Mexico',
  'Monaco',
  'Morocco',
  'Mauritius',
  'Mauritania',
  'Mozambique',
  'Montenegro',
  'Montserrat',
  'Moldova, Republic of',
  'Maldives',
  'Malta',
  'Mongolia',
  'United States',
  'United States Minor Outlying Islands',
  'Virgin Islands, U.S.',
  'Myanmar',
  'Micronesia',
  'Vanuatu',
  'Bahrain',
  'Barbados',
  'Vatican City State',
  'Bahamas',
  'Bangladesh',
  'Bermuda',
  'Benin',
  'Venezuela',
  'Viet Nam',
  'Belgium',
  'Belarus',
  'Belize',
  'Bosnia Hercegovina',
  'Botswana',
  'Bolivia',
  'Burundi',
  'Burkina Faso',
  'Bouvet Island',
  'Bhutan',
  'Northern Mariana Islands',
  'Bulgaria',
  'Brazil',
  'Brunei Darussalam',
  'Samoa',
  'Saudi Arabia',
  'South Georgia and the South Sandwich Islands',
  'San Marino',
  'Sao Tome and Principe',
  'St. Pierre and Miquelon',
  'Western Sahara',
  'Senegal',
  'Serbia',
  'Seychelles',
  'Saint Lucia',
  'Saint Vincent and the Grenadines',
  'Saint Kitts and Nevis',
  'St. Helena',
  'Somalia',
  'Solomon Islands',
  'Sudan',
  'Suriname',
  'Sri Lanka',
  'Svalbard and Jan Mayen Islands',
  'Swaziland',
  'Sweden',
  'Switzerland',
  'Spain',
  'Slovakia',
  'Slovenia',
  'Syrian Arab Republic',
  'Sierra Leone',
  'Singapore',
  'United Arab Emirates',
  'Aruba',
  'Armenia',
  'Argentina',
  'American Samoa',
  'Iceland',
  'Haiti',
  'Ireland',
  'Azerbaijan',
  'Afghanistan',
  'Andorra',
  'Albania',
  'Algeria',
  'Angola',
  'Antigua and Barbuda',
  'Anguilla',
  'Eritrea',
  'Estonia',
  'Ecuador',
  'Ethiopia',
  'El Salvador',
  'United Kingdom',
  'Virgin Islands, British',
  'British Indian Ocean Territory',
  'Yemen, Republic of',
  'Oman',
  'Australia',
  'Austria',
  'Honduras',
  'Aland Islands',
  'Wallis and Futuna Islands',
  'Jordan',
  'Uganda',
  'Uruguay',
  'Uzbekistan',
  'Ukraine',
  'Iraq',
  'Iran',
  'Israel',
  'Egypt',
  'Italy',
  'India',
  'Indonesia',
  'Japan',
  'Jamaica',
  'Zambia',
  'Jersey',
  'Equatorial Guinea',
  "Korea, Democratic People's Republic of",
  'Georgia',
  'Central African Republic',
  'Taiwan, Province of China',
  'China',
  'Djibouti',
  'Gibraltar',
  'Zimbabwe',
  'Chad',
  'Czech Republic',
  'Chile',
  'Cameroon',
  'Cape Verde',
  'Kazakhstan',
  'Qatar',
  'Cambodia',
  'Canada',
  'Kenya',
  'Cayman Islands',
  'Comoros',
  'Costa Rica',
  'Cocos Islands',
  "Cote d'Ivoire",
  'Colombia',
  'Congo',
  'Democratic Republic of the Congo',
  'Cuba',
  'Kuwait',
  'Cook Islands',
  'Croatia',
  'Christmas Island',
  'Kyrgyzstan',
  'Kiribati',
  'Cyprus',
  'Thailand',
  'Tajikistan',
  'Tanzania, United Republic of',
  'Turks and Caicos Islands',
  'Turkey',
  'Togo',
  'Tokelau',
  'Tonga',
  'Turkmenistan',
  'Tuvalu',
  'Tunisia',
  'Trinidad and Tobago',
  'Panama',
  'Paraguay',
  'Pakistan',
  'Papua New Guinea',
  'Palau',
  'Palestine',
  'Faroe Islands',
  'Peru',
  'Portugal',
  'Falkland Islands',
  'Poland',
  'Puerto Rico',
  'France',
  'French Guiana',
  'French Southern Territories',
  'French Polynesia',
  'Fiji',
  'Finland',
  'Philippines',
  'Pitcairn',
  'Heard and McDonald Islands',
  'Hungary',
  'Hong Kong',
];
