import { EtcLanguageData } from '@/types/manageResume/manageResume';

export const LanguageList: EtcLanguageData[] = [
  {
    id: 1,
    country_name: '아랍',
    language: 'Arabic',
    img_url: '/src/assets/images/countryImg/SA.png',
  },
  {
    id: 2,
    country_name: '불가리아',
    language: 'Bulgarian',
    img_url: '/src/assets/images/countryImg/BG.png',
  },
  {
    id: 3,
    country_name: '중국',
    language: 'Chinese',
    img_url: '/src/assets/images/countryImg/CN.png',
  },
  {
    id: 4,
    country_name: '체코',
    language: 'Czech',
    img_url: '/src/assets/images/countryImg/CZ.png',
  },
  {
    id: 5,
    country_name: '덴마크',
    language: 'Danish',
    img_url: '/src/assets/images/countryImg/DK.png',
  },
  {
    id: 6,
    country_name: '네덜란드',
    language: 'Dutch',
    img_url: '/src/assets/images/countryImg/NL.png',
  },
  {
    id: 7,
    country_name: '영국',
    language: 'English',
    img_url: '/src/assets/images/countryImg/GB.png',
  },
  {
    id: 8,
    country_name: '에스토니아',
    language: 'Estonian',
    img_url: '/src/assets/images/countryImg/EE.png',
  },
  {
    id: 9,
    country_name: '핀란드',
    language: 'Finnish',
    img_url: '/src/assets/images/countryImg/FI.png',
  },
  {
    id: 10,
    country_name: '프랑스',
    language: 'French',
    img_url: '/src/assets/images/countryImg/FR.png',
  },
  {
    id: 11,
    country_name: '독일',
    language: 'German',
    img_url: '/src/assets/images/countryImg/DE.png',
  },
  {
    id: 12,
    country_name: '그리스',
    language: 'Greek',
    img_url: '/src/assets/images/countryImg/GR.png',
  },
  {
    id: 13,
    country_name: '헝가리',
    language: 'Hungarian',
    img_url: '/src/assets/images/countryImg/HU.png',
  },
  {
    id: 14,
    country_name: '인도네시아',
    language: 'Indonesian',
    img_url: '/src/assets/images/countryImg/ID.png',
  },
  {
    id: 15,
    country_name: '이탈리아',
    language: 'Italian',
    img_url: '/src/assets/images/countryImg/IT.png',
  },
  {
    id: 16,
    country_name: '일본',
    language: 'Japanese',
    img_url: '/src/assets/images/countryImg/JP.png',
  },
  {
    id: 17,
    country_name: '한국',
    language: 'Korean',
    img_url: '/src/assets/images/countryImg/KR.png',
  },
  {
    id: 18,
    country_name: '라트비아',
    language: 'Latvian',
    img_url: '/src/assets/images/countryImg/LV.png',
  },
  {
    id: 19,
    country_name: '라투아니아',
    language: 'Lithuanian',
    img_url: '/src/assets/images/countryImg/LT.png',
  },
  {
    id: 20,
    country_name: '노르웨이',
    language: 'Norwegian',
    img_url: '/src/assets/images/countryImg/NO.png',
  },
  {
    id: 21,
    country_name: '폴란드',
    language: 'Polish',
    img_url: '/src/assets/images/countryImg/PL.png',
  },
  {
    id: 22,
    country_name: '포르투갈',
    language: 'Portuguese',
    img_url: '/src/assets/images/countryImg/PT.png',
  },
  {
    id: 23,
    country_name: '루마니아',
    language: 'Romanian',
    img_url: '/src/assets/images/countryImg/RO.png',
  },
  {
    id: 24,
    country_name: '러시아',
    language: 'Russian',
    img_url: '/src/assets/images/countryImg/RU.png',
  },
  {
    id: 25,
    country_name: '슬로바키아',
    language: 'Slovak',
    img_url: '/src/assets/images/countryImg/SK.png',
  },
  {
    id: 9,
    country_name: '슬로베니아',
    language: 'Slovenian',
    img_url: '/src/assets/images/countryImg/SI.png',
  },
  {
    id: 26,
    country_name: '스페인',
    language: 'Spanish',
    img_url: '/src/assets/images/countryImg/ES.png',
  },
  {
    id: 27,
    country_name: '스웨덴',
    language: 'Swedish',
    img_url: '/src/assets/images/countryImg/SE.png',
  },
  {
    id: 28,
    country_name: '튀르키예',
    language: 'Turkic',
    img_url: '/src/assets/images/countryImg/TR.png',
  },
  {
    id: 29,
    country_name: '우크라이나',
    language: 'Ukrainian',
    img_url: '/src/assets/images/countryImg/UA.png',
  },
];
